spring:
  mail:
    default-encoding: UTF-8
    host: localhost
    jndi-name:
    username: eric@copyvic.com.br
    password: 159901df
    port: 2525
    properties:
      mail:
        debug: false
        smtp:
          debug: false
          auth: true
          starttls: true
    protocol: smtp
    test-connection: false